-- ============================================================
-- TEACHER SETUP — PART 2 OF 2
--
-- Run part 1 first, in its own query tab.
--
-- Paste this whole file into a new Supabase SQL editor tab and run it.
-- It creates the classroom tables, the dashboard functions, answer
-- capture, and the access-code limits. It is safe to re-run: every
-- statement is guarded with IF NOT EXISTS or CREATE OR REPLACE.
--
-- Source: 11 files from supabase/migrations, concatenated
-- in filename order.
--
-- Generated by scripts/build-teacher-sql.mjs — do not edit by hand.
-- Edit the files in supabase/migrations and regenerate.
-- ============================================================

-- Classrooms: the teacher-facing grouping built on top of the existing
-- access-code system.
--
-- An access code already links every student to a cohort via
-- profiles.signup_access_code. This migration promotes that implicit grouping
-- into a real entity a teacher can own, name, and manage a roster for, while
-- keeping the student sign-up flow completely unchanged: classrooms.join_code
-- mirrors access_codes.code, so the code a student already types at sign-up is
-- the code that puts them in a classroom.

-- ── 1) classrooms ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.classrooms (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Nullable: classrooms backfilled from pre-existing access codes have no
  -- owner until an admin assigns one.
  teacher_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name         TEXT NOT NULL,
  join_code    TEXT NOT NULL UNIQUE,
  school_name  TEXT,
  term         TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  archived_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS classrooms_teacher_id_idx ON public.classrooms (teacher_id);
CREATE INDEX IF NOT EXISTS classrooms_join_code_idx  ON public.classrooms (join_code);

DROP TRIGGER IF EXISTS classrooms_set_updated_at ON public.classrooms;
CREATE TRIGGER classrooms_set_updated_at
  BEFORE UPDATE ON public.classrooms
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ── 2) classroom_members ─────────────────────────────────────────────────────
-- An explicit roster, rather than deriving membership from
-- profiles.signup_access_code on every read. This lets a teacher remove a
-- student who joined with the wrong code without touching the code itself.
CREATE TABLE IF NOT EXISTS public.classroom_members (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id UUID NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  student_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
  joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (classroom_id, student_id)
);

CREATE INDEX IF NOT EXISTS classroom_members_classroom_idx ON public.classroom_members (classroom_id);
CREATE INDEX IF NOT EXISTS classroom_members_student_idx   ON public.classroom_members (student_id);

-- ── 3) access_codes gains a classroom link and a role grant ──────────────────
-- grants_role lets one table serve both audiences: student codes grant 'user',
-- admin-issued teacher codes grant 'teacher'.
ALTER TABLE public.access_codes
  ADD COLUMN IF NOT EXISTS classroom_id UUID REFERENCES public.classrooms(id) ON DELETE SET NULL;

ALTER TABLE public.access_codes
  ADD COLUMN IF NOT EXISTS grants_role public.app_role NOT NULL DEFAULT 'user';

-- ── 4) Ownership guard ───────────────────────────────────────────────────────
-- The single authorization check shared by classroom RLS and every teacher_*
-- RPC. SECURITY DEFINER so it can read classrooms without tripping that
-- table's own RLS (the same pattern as public.has_role).
CREATE OR REPLACE FUNCTION public.teacher_owns_classroom(p_classroom_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.classrooms c
    WHERE c.id = p_classroom_id
      AND c.teacher_id = auth.uid()
  ) OR public.is_phil_admin();
$$;

GRANT EXECUTE ON FUNCTION public.teacher_owns_classroom(UUID) TO authenticated;

-- ── 5) RLS ───────────────────────────────────────────────────────────────────
ALTER TABLE public.classrooms        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_members ENABLE ROW LEVEL SECURITY;

-- Teachers manage their own classrooms. Direct teacher_id comparison rather
-- than the helper, so the policy can never recurse into itself.
DROP POLICY IF EXISTS "Teachers manage their own classrooms" ON public.classrooms;
CREATE POLICY "Teachers manage their own classrooms"
ON public.classrooms
FOR ALL
TO authenticated
USING (teacher_id = auth.uid() OR public.is_phil_admin())
WITH CHECK (teacher_id = auth.uid() OR public.is_phil_admin());

-- Students may read the classroom they belong to (for a "your class" label).
DROP POLICY IF EXISTS "Students can view their own classroom" ON public.classrooms;
CREATE POLICY "Students can view their own classroom"
ON public.classrooms
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.classroom_members m
    WHERE m.classroom_id = classrooms.id
      AND m.student_id = auth.uid()
      AND m.status = 'active'
  )
);

DROP POLICY IF EXISTS "Teachers manage their classroom roster" ON public.classroom_members;
CREATE POLICY "Teachers manage their classroom roster"
ON public.classroom_members
FOR ALL
TO authenticated
USING (public.teacher_owns_classroom(classroom_id))
WITH CHECK (public.teacher_owns_classroom(classroom_id));

DROP POLICY IF EXISTS "Students can view their own membership" ON public.classroom_members;
CREATE POLICY "Students can view their own membership"
ON public.classroom_members
FOR SELECT
TO authenticated
USING (student_id = auth.uid());

-- ── 6) Backfill from existing access codes ───────────────────────────────────
-- Every code that already exists becomes a classroom, so existing cohorts show
-- up on day one with no student action required.
INSERT INTO public.classrooms (name, join_code, created_at)
SELECT COALESCE(NULLIF(btrim(ac.label), ''), ac.code), ac.code, COALESCE(ac.created_at, now())
FROM public.access_codes ac
WHERE ac.grants_role = 'user'
ON CONFLICT (join_code) DO NOTHING;

UPDATE public.access_codes ac
SET classroom_id = c.id
FROM public.classrooms c
WHERE c.join_code = ac.code
  AND ac.classroom_id IS NULL;

-- Enroll everyone who signed up with each code.
INSERT INTO public.classroom_members (classroom_id, student_id, joined_at)
SELECT c.id, p.id, COALESCE(p.created_at, now())
FROM public.profiles p
JOIN public.classrooms c ON c.join_code = upper(btrim(p.signup_access_code))
WHERE p.signup_access_code IS NOT NULL
ON CONFLICT (classroom_id, student_id) DO NOTHING;

-- ── 7) Keep the roster in sync as new students sign up ───────────────────────
-- handle_new_user() writes profiles.signup_access_code; this trigger turns that
-- into a roster row so enrollment never depends on client code running.
CREATE OR REPLACE FUNCTION public.sync_classroom_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_classroom_id UUID;
BEGIN
  IF NEW.signup_access_code IS NULL OR btrim(NEW.signup_access_code) = '' THEN
    RETURN NEW;
  END IF;

  SELECT id INTO v_classroom_id
  FROM public.classrooms
  WHERE join_code = upper(btrim(NEW.signup_access_code))
  LIMIT 1;

  IF v_classroom_id IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.classroom_members (classroom_id, student_id)
  VALUES (v_classroom_id, NEW.id)
  ON CONFLICT (classroom_id, student_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_sync_classroom_membership ON public.profiles;
CREATE TRIGGER profiles_sync_classroom_membership
  AFTER INSERT OR UPDATE OF signup_access_code ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.sync_classroom_membership();


-- ------------------------------------------------------------
-- 20260801000200_teacher_rpcs.sql
-- ------------------------------------------------------------
-- Teacher dashboard read APIs.
--
-- Every progress table in this schema is RLS-restricted to
-- `auth.uid() = user_id`, so a teacher cannot read their students' rows
-- directly. These SECURITY DEFINER functions follow the pattern already
-- established by admin_list_code_users: check authorization first, then return
-- only rows belonging to students on the caller's own roster.
--
-- Student email is deliberately absent from the roster listing. It appears only
-- in teacher_get_student_detail, where a teacher has explicitly drilled into one
-- student.

-- ── Role helper ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.is_teacher()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.has_role(auth.uid(), 'teacher') OR public.is_phil_admin();
$$;

GRANT EXECUTE ON FUNCTION public.is_teacher() TO authenticated;

-- ── Classrooms the caller teaches ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.teacher_list_classrooms()
RETURNS TABLE (
  id            UUID,
  name          TEXT,
  join_code     TEXT,
  school_name   TEXT,
  term          TEXT,
  is_active     BOOLEAN,
  created_at    TIMESTAMPTZ,
  student_count BIGINT,
  active_last_7 BIGINT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_teacher() THEN
    RAISE EXCEPTION 'Teacher access required';
  END IF;

  RETURN QUERY
    SELECT
      c.id,
      c.name,
      c.join_code,
      c.school_name,
      c.term,
      c.is_active,
      c.created_at,
      COALESCE(counts.student_count, 0),
      COALESCE(counts.active_last_7, 0)
    FROM public.classrooms c
    LEFT JOIN LATERAL (
      SELECT
        COUNT(*) AS student_count,
        COUNT(*) FILTER (
          WHERE EXISTS (
            SELECT 1 FROM public.daily_logins d
            WHERE d.user_id = m.student_id
              AND d.login_date >= CURRENT_DATE - 6
          )
        ) AS active_last_7
      FROM public.classroom_members m
      WHERE m.classroom_id = c.id
        AND m.status = 'active'
    ) counts ON TRUE
    WHERE c.teacher_id = auth.uid()
    ORDER BY c.is_active DESC, c.created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_list_classrooms() TO authenticated;

-- ── Roster with headline metrics per student ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.teacher_get_roster(p_classroom_id UUID)
RETURNS TABLE (
  student_id              UUID,
  username                TEXT,
  joined_at               TIMESTAMPTZ,
  last_login_date         DATE,
  current_streak          INTEGER,
  longest_streak          INTEGER,
  total_points            INTEGER,
  modules_completed       BIGINT,
  modules_in_progress     BIGINT,
  avg_progress            NUMERIC,
  career_levels_completed BIGINT,
  teach_backs_completed   INTEGER,
  days_active_30          BIGINT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom';
  END IF;

  RETURN QUERY
    SELECT
      m.student_id,
      p.username,
      m.joined_at,
      p.last_login_date,
      COALESCE(p.current_streak, 0),
      COALESCE(p.longest_streak, 0),
      COALESCE(up.total_points, 0),
      COALESCE(mods.completed, 0),
      COALESCE(mods.in_progress, 0),
      COALESCE(mods.avg_progress, 0),
      COALESCE(careers.levels, 0),
      COALESCE(p.teach_backs_completed, 0),
      COALESCE(logins.days_active, 0)
    FROM public.classroom_members m
    JOIN public.profiles p ON p.id = m.student_id
    LEFT JOIN public.user_progress up ON up.user_id = m.student_id
    LEFT JOIN LATERAL (
      SELECT
        COUNT(*) FILTER (WHERE x.progress_percentage >= 100) AS completed,
        COUNT(*) FILTER (WHERE x.progress_percentage > 0 AND x.progress_percentage < 100) AS in_progress,
        ROUND(COALESCE(AVG(x.progress_percentage), 0)) AS avg_progress
      FROM public.module_progress x
      WHERE x.user_id = m.student_id
    ) mods ON TRUE
    LEFT JOIN LATERAL (
      SELECT COUNT(*) AS levels
      FROM public.lesson_completions lc
      WHERE lc.user_id = m.student_id
    ) careers ON TRUE
    LEFT JOIN LATERAL (
      SELECT COUNT(*) AS days_active
      FROM public.daily_logins d
      WHERE d.user_id = m.student_id
        AND d.login_date >= CURRENT_DATE - 29
    ) logins ON TRUE
    WHERE m.classroom_id = p_classroom_id
      AND m.status = 'active'
    ORDER BY p.username NULLS LAST;
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_roster(UUID) TO authenticated;

-- ── Per-student, per-module progress (the completion matrix) ─────────────────
CREATE OR REPLACE FUNCTION public.teacher_get_module_matrix(p_classroom_id UUID)
RETURNS TABLE (
  student_id          UUID,
  module_id           TEXT,
  module_type         TEXT,
  progress_percentage INTEGER,
  completed_at        TIMESTAMPTZ,
  last_accessed       TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom';
  END IF;

  RETURN QUERY
    SELECT
      mp.user_id,
      mp.module_id,
      mp.module_type,
      COALESCE(mp.progress_percentage, 0),
      mp.completed_at,
      mp.last_accessed
    FROM public.module_progress mp
    JOIN public.classroom_members m
      ON m.student_id = mp.user_id
     AND m.classroom_id = p_classroom_id
     AND m.status = 'active';
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_module_matrix(UUID) TO authenticated;

-- ── Login activity for the engagement heatmap ────────────────────────────────
CREATE OR REPLACE FUNCTION public.teacher_get_activity(
  p_classroom_id UUID,
  p_days INTEGER DEFAULT 30
)
RETURNS TABLE (
  student_id UUID,
  login_date DATE
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days INTEGER := LEAST(GREATEST(COALESCE(p_days, 30), 1), 365);
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom';
  END IF;

  RETURN QUERY
    SELECT d.user_id, d.login_date
    FROM public.daily_logins d
    JOIN public.classroom_members m
      ON m.student_id = d.user_id
     AND m.classroom_id = p_classroom_id
     AND m.status = 'active'
    WHERE d.login_date >= CURRENT_DATE - (v_days - 1);
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_activity(UUID, INTEGER) TO authenticated;

-- ── One student, everything ──────────────────────────────────────────────────
-- Returned as a single JSONB document so the detail panel opens in one round
-- trip instead of five.
CREATE OR REPLACE FUNCTION public.teacher_get_student_detail(
  p_classroom_id UUID,
  p_student_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.classroom_members m
    WHERE m.classroom_id = p_classroom_id
      AND m.student_id = p_student_id
      AND m.status = 'active'
  ) THEN
    RAISE EXCEPTION 'Student is not on this roster';
  END IF;

  SELECT jsonb_build_object(
    'profile', (
      SELECT jsonb_build_object(
        'student_id', p.id,
        'username', p.username,
        'email', p.email,
        'joined_at', m.joined_at,
        'created_at', p.created_at,
        'last_login_date', p.last_login_date,
        'current_streak', COALESCE(p.current_streak, 0),
        'longest_streak', COALESCE(p.longest_streak, 0),
        'total_points', COALESCE(up.total_points, 0),
        'engagement_score', COALESCE(up.engagement_score, 0),
        'teach_backs_completed', COALESCE(p.teach_backs_completed, 0)
      )
      FROM public.profiles p
      JOIN public.classroom_members m
        ON m.student_id = p.id AND m.classroom_id = p_classroom_id
      LEFT JOIN public.user_progress up ON up.user_id = p.id
      WHERE p.id = p_student_id
    ),
    'modules', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'module_id', mp.module_id,
        'module_type', mp.module_type,
        'course_id', mp.course_id,
        'progress_percentage', COALESCE(mp.progress_percentage, 0),
        'time_spent_minutes', COALESCE(mp.time_spent_minutes, 0),
        'pre_test_score', mp.pre_test_score,
        'post_test_score', mp.post_test_score,
        'last_accessed', mp.last_accessed,
        'completed_at', mp.completed_at
      ) ORDER BY mp.last_accessed DESC NULLS LAST)
      FROM public.module_progress mp
      WHERE mp.user_id = p_student_id
    ), '[]'::jsonb),
    'careers', COALESCE((
      SELECT jsonb_agg(c)
      FROM (
        SELECT jsonb_build_object(
          'career_id', lc.career_id,
          'levels_completed', COUNT(*),
          'last_completed_at', MAX(lc.completed_at)
        ) AS c
        FROM public.lesson_completions lc
        WHERE lc.user_id = p_student_id
        GROUP BY lc.career_id
        ORDER BY COUNT(*) DESC
      ) careers_agg
    ), '[]'::jsonb),
    'recent_xp', COALESCE((
      SELECT jsonb_agg(x)
      FROM (
        SELECT jsonb_build_object(
          'xp_amount', xt.xp_amount,
          'source', xt.source,
          'created_at', xt.created_at
        ) AS x
        FROM public.xp_transactions xt
        WHERE xt.user_id = p_student_id
        ORDER BY xt.created_at DESC
        LIMIT 25
      ) xp_agg
    ), '[]'::jsonb),
    'teach_backs', COALESCE((
      SELECT jsonb_agg(t)
      FROM (
        SELECT jsonb_build_object(
          'lesson_id', tb.lesson_id,
          'difficulty_tier', tb.difficulty_tier,
          'final_understanding_score', tb.final_understanding_score,
          'passed', tb.passed,
          'key_facts_missing', tb.key_facts_missing,
          'created_at', tb.created_at
        ) AS t
        FROM public.teach_back_sessions tb
        WHERE tb.user_id = p_student_id
        ORDER BY tb.created_at DESC
        LIMIT 20
      ) tb_agg
    ), '[]'::jsonb),
    'activity', COALESCE((
      SELECT jsonb_agg(d.login_date ORDER BY d.login_date)
      FROM public.daily_logins d
      WHERE d.user_id = p_student_id
        AND d.login_date >= CURRENT_DATE - 59
    ), '[]'::jsonb)
  ) INTO v_result;

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_student_detail(UUID, UUID) TO authenticated;

-- ── Where the class as a whole is struggling ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.teacher_get_class_insights(p_classroom_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom';
  END IF;

  SELECT jsonb_build_object(
    'modules', COALESCE((
      SELECT jsonb_agg(m)
      FROM (
        SELECT jsonb_build_object(
          'module_id', mp.module_id,
          'module_type', mp.module_type,
          'students_started', COUNT(*),
          'students_completed', COUNT(*) FILTER (WHERE mp.progress_percentage >= 100),
          'avg_progress', ROUND(COALESCE(AVG(mp.progress_percentage), 0)),
          'avg_post_test_score', ROUND(AVG(mp.post_test_score))
        ) AS m
        FROM public.module_progress mp
        JOIN public.classroom_members cm
          ON cm.student_id = mp.user_id
         AND cm.classroom_id = p_classroom_id
         AND cm.status = 'active'
        GROUP BY mp.module_id, mp.module_type
        ORDER BY AVG(mp.progress_percentage) ASC
      ) module_agg
    ), '[]'::jsonb),
    'concept_gaps', COALESCE((
      SELECT jsonb_agg(g)
      FROM (
        SELECT jsonb_build_object(
          'fact', f.fact,
          'miss_count', COUNT(*),
          'student_count', COUNT(DISTINCT tb.user_id)
        ) AS g
        FROM public.teach_back_sessions tb
        JOIN public.classroom_members cm
          ON cm.student_id = tb.user_id
         AND cm.classroom_id = p_classroom_id
         AND cm.status = 'active'
        CROSS JOIN LATERAL jsonb_array_elements_text(tb.key_facts_missing) AS f(fact)
        GROUP BY f.fact
        ORDER BY COUNT(*) DESC
        LIMIT 12
      ) gap_agg
    ), '[]'::jsonb)
  ) INTO v_result;

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_class_insights(UUID) TO authenticated;

-- ── Creating a classroom ─────────────────────────────────────────────────────
-- A teacher needs a sign-up code to hand out, but access_codes is admin-only by
-- RLS. This creates the classroom and its matching student code together, so a
-- teacher never touches the access_codes table directly.
CREATE OR REPLACE FUNCTION public.teacher_create_classroom(
  p_name TEXT,
  p_school_name TEXT DEFAULT NULL,
  p_term TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_alphabet CONSTANT TEXT := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; -- no 0/O/1/I/L
  v_code TEXT;
  v_classroom_id UUID;
  v_name TEXT := NULLIF(btrim(COALESCE(p_name, '')), '');
  v_attempt INTEGER := 0;
BEGIN
  IF NOT public.is_teacher() THEN
    RAISE EXCEPTION 'Teacher access required';
  END IF;

  IF v_name IS NULL THEN
    RAISE EXCEPTION 'Classroom name is required';
  END IF;

  -- Retry on the (unlikely) collision rather than trusting one draw.
  LOOP
    v_attempt := v_attempt + 1;
    SELECT 'CLASS-' || string_agg(
             substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::int, 1), ''
           )
      INTO v_code
      FROM generate_series(1, 4);

    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.classrooms WHERE join_code = v_code)
          AND NOT EXISTS (SELECT 1 FROM public.access_codes WHERE code = v_code);

    IF v_attempt > 20 THEN
      RAISE EXCEPTION 'Could not allocate a unique class code';
    END IF;
  END LOOP;

  INSERT INTO public.classrooms (teacher_id, name, join_code, school_name, term)
  VALUES (auth.uid(), v_name, v_code, NULLIF(btrim(COALESCE(p_school_name, '')), ''),
          NULLIF(btrim(COALESCE(p_term, '')), ''))
  RETURNING id INTO v_classroom_id;

  INSERT INTO public.access_codes (code, label, classroom_id, grants_role, created_by)
  VALUES (v_code, v_name, v_classroom_id, 'user', auth.uid());

  RETURN jsonb_build_object('id', v_classroom_id, 'join_code', v_code, 'name', v_name);
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_create_classroom(TEXT, TEXT, TEXT) TO authenticated;

-- ── Consistency fix ──────────────────────────────────────────────────────────
-- 20260629010000 rewrote admin_list_code_users to accept the owner email via
-- is_phil_admin(), but 20260630000000 ran afterwards and reverted it to a plain
-- has_role() check — so the owner-email path fails on this one RPC while it
-- works everywhere else. Restore the intended check.
CREATE OR REPLACE FUNCTION public.admin_list_code_users(p_code TEXT)
RETURNS TABLE (username TEXT, email TEXT, created_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_phil_admin() THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  RETURN QUERY
    SELECT p.username, p.email, p.created_at
    FROM public.profiles p
    WHERE p.signup_access_code = upper(btrim(p_code))
    ORDER BY p.created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_code_users(TEXT) TO authenticated;


-- ------------------------------------------------------------
-- 20260801000300_sync_module_progress.sql
-- ------------------------------------------------------------
-- Write-through sync for the curriculum areas that only ever persisted to
-- localStorage (Market Intelligence village lessons, the MI catalog, the
-- economics units, and career readiness). Without this a teacher dashboard can
-- only see Personal Finance, because nothing else reaches the database.
--
-- Why an RPC instead of a client-side upsert:
--
--   1. module_progress is UNIQUE (user_id, module_id, module_type, course_id)
--      and course_id is NULL for all of these. NULLs are distinct in a unique
--      index, so ON CONFLICT would never match and every save would insert a
--      duplicate row.
--
--   2. Progress must only ever move forward. A student signing in on a fresh
--      device starts with empty localStorage; a naive write-through would push
--      0% and wipe out real progress. The monotonic guard below makes that
--      impossible.

CREATE OR REPLACE FUNCTION public.sync_module_progress(p_entries JSONB)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_entry JSONB;
  v_module_id TEXT;
  v_module_type TEXT;
  v_percent INTEGER;
  v_detail JSONB;
  v_existing INTEGER;
  v_written INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_entries IS NULL OR jsonb_typeof(p_entries) <> 'array' THEN
    RETURN 0;
  END IF;

  FOR v_entry IN SELECT * FROM jsonb_array_elements(p_entries)
  LOOP
    v_module_id   := NULLIF(btrim(COALESCE(v_entry ->> 'module_id', '')), '');
    v_module_type := NULLIF(btrim(COALESCE(v_entry ->> 'module_type', '')), '');
    v_percent     := LEAST(GREATEST(COALESCE((v_entry ->> 'progress_percentage')::int, 0), 0), 100);
    v_detail      := COALESCE(v_entry -> 'detailed_progress', '{}'::jsonb);

    CONTINUE WHEN v_module_id IS NULL OR v_module_type IS NULL;

    SELECT mp.progress_percentage INTO v_existing
    FROM public.module_progress mp
    WHERE mp.user_id = v_uid
      AND mp.module_id = v_module_id
      AND mp.module_type = v_module_type
      AND mp.course_id IS NULL;

    IF FOUND THEN
      -- Only move forward, and skip no-op writes entirely.
      CONTINUE WHEN v_percent <= COALESCE(v_existing, 0);

      UPDATE public.module_progress mp
      SET progress_percentage = v_percent,
          detailed_progress = v_detail,
          completed_at = CASE WHEN v_percent >= 100 THEN COALESCE(mp.completed_at, now()) ELSE mp.completed_at END,
          last_accessed = now(),
          updated_at = now()
      WHERE mp.user_id = v_uid
        AND mp.module_id = v_module_id
        AND mp.module_type = v_module_type
        AND mp.course_id IS NULL;
    ELSE
      -- Nothing to record for an untouched module.
      CONTINUE WHEN v_percent <= 0;

      INSERT INTO public.module_progress (
        user_id, module_id, module_type, progress_percentage,
        detailed_progress, completed_at, last_accessed
      )
      VALUES (
        v_uid, v_module_id, v_module_type, v_percent,
        v_detail,
        CASE WHEN v_percent >= 100 THEN now() ELSE NULL END,
        now()
      );
    END IF;

    v_written := v_written + 1;
  END LOOP;

  RETURN v_written;
END;
$$;

GRANT EXECUTE ON FUNCTION public.sync_module_progress(JSONB) TO authenticated;


-- ------------------------------------------------------------
-- 20260801000400_teacher_signup.sql
-- ------------------------------------------------------------
-- Teacher provisioning at sign-up.
--
-- Teacher access is an admin step, not self-serve: Phil issues a code with
-- grants_role = 'teacher' from the admin screen, and whoever redeems it gets
-- the teacher role assigned by this trigger. There is no client-side path to
-- becoming a teacher.

-- Tracks completion of the teacher-specific onboarding branch (name the school,
-- create the first classroom), the way survey_completed / app_tour_completed do
-- for students.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS teacher_setup_completed BOOLEAN NOT NULL DEFAULT FALSE;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_code text := upper(btrim(COALESCE(NEW.raw_user_meta_data ->> 'access_code', '')));
  v_id uuid;
  v_role public.app_role;
BEGIN
  -- Require a valid, active access code. Raises (and rolls back the signup)
  -- if missing or invalid — this is the server-side backstop for the gate.
  SELECT id, grants_role INTO v_id, v_role
  FROM public.access_codes
  WHERE code = v_code
    AND is_active = TRUE
  LIMIT 1;

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'A valid access code is required to create an account.'
      USING ERRCODE = 'check_violation';
  END IF;

  -- Redeem (count the signup).
  UPDATE public.access_codes
  SET redeemed_count = redeemed_count + 1
  WHERE id = v_id;

  INSERT INTO public.profiles (id, email, username, signup_access_code)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'username', split_part(NEW.email, '@', 1)),
    v_code
  );

  INSERT INTO public.user_progress (user_id)
  VALUES (NEW.id);

  -- Codes that grant a privileged role do so here, server-side. 'user' is the
  -- implicit default and needs no row.
  IF v_role IS NOT NULL AND v_role <> 'user' THEN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, v_role)
    ON CONFLICT (user_id, role) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;


-- ------------------------------------------------------------
-- 20260802000000_access_code_lifecycle.sql
-- ------------------------------------------------------------
-- Access code lifecycle: expiry dates and redemption caps.
--
-- Until now a code was a permanent, unlimited-use credential: once issued it
-- worked forever for anyone who had the string. That is tolerable for a student
-- code handed to one class, and not tolerable for a teacher code, which grants
-- the ability to see student data. A leaked TEACH- code could mint teacher
-- accounts indefinitely.
--
-- Adds two optional limits (NULL on either means "no limit", preserving the
-- behaviour of every code issued so far) and enforces both in the two places
-- codes are checked: the pre-flight validation the sign-up form calls, and the
-- handle_new_user trigger that is the actual gate.

ALTER TABLE public.access_codes
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS max_redemptions INTEGER;

ALTER TABLE public.access_codes
  DROP CONSTRAINT IF EXISTS access_codes_max_redemptions_positive;
ALTER TABLE public.access_codes
  ADD CONSTRAINT access_codes_max_redemptions_positive
  CHECK (max_redemptions IS NULL OR max_redemptions > 0);

COMMENT ON COLUMN public.access_codes.expires_at IS
  'After this moment the code stops working for new sign-ups. NULL = never expires.';
COMMENT ON COLUMN public.access_codes.max_redemptions IS
  'Cap on total sign-ups. NULL = unlimited. Teacher codes should normally be 1.';

-- ============================================================
-- Shared redeemability test, so the form check and the trigger
-- can never drift apart on what "usable" means.
-- ============================================================
CREATE OR REPLACE FUNCTION public.access_code_is_redeemable(p_code TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.access_codes
    WHERE code = upper(btrim(p_code))
      AND is_active = TRUE
      AND (expires_at IS NULL OR expires_at > now())
      AND (max_redemptions IS NULL OR redeemed_count < max_redemptions)
  );
$$;

GRANT EXECUTE ON FUNCTION public.access_code_is_redeemable(TEXT) TO anon, authenticated;

-- check_access_code is what the sign-up form calls before attempting signUp.
-- Same answer, kept under the old name so no client change is required.
CREATE OR REPLACE FUNCTION public.check_access_code(p_code TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.access_code_is_redeemable(p_code);
$$;

GRANT EXECUTE ON FUNCTION public.check_access_code(TEXT) TO anon, authenticated;

-- ============================================================
-- handle_new_user — the real gate. Now rejects expired and
-- exhausted codes, with distinguishable messages so a student
-- who mistyped is told something different from a student whose
-- teacher's code ran out.
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_code text := upper(btrim(COALESCE(NEW.raw_user_meta_data ->> 'access_code', '')));
  v_id uuid;
  v_role public.app_role;
  v_expires_at timestamptz;
  v_redeemed uuid;
BEGIN
  SELECT id, grants_role, expires_at
    INTO v_id, v_role, v_expires_at
  FROM public.access_codes
  WHERE code = v_code
    AND is_active = TRUE
  LIMIT 1;

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'A valid access code is required to create an account.'
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_expires_at IS NOT NULL AND v_expires_at <= now() THEN
    RAISE EXCEPTION 'That access code has expired. Ask your teacher for a current one.'
      USING ERRCODE = 'check_violation';
  END IF;

  -- Redeem and enforce the cap in one statement so two simultaneous sign-ups
  -- on the last remaining slot cannot both succeed.
  UPDATE public.access_codes
  SET redeemed_count = redeemed_count + 1
  WHERE id = v_id
    AND (max_redemptions IS NULL OR redeemed_count < max_redemptions)
  RETURNING id INTO v_redeemed;

  IF v_redeemed IS NULL THEN
    RAISE EXCEPTION 'That access code has already been used the maximum number of times.'
      USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.profiles (id, email, username, signup_access_code)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'username', split_part(NEW.email, '@', 1)),
    v_code
  );

  INSERT INTO public.user_progress (user_id)
  VALUES (NEW.id);

  IF v_role IS NOT NULL AND v_role <> 'user' THEN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, v_role)
    ON CONFLICT (user_id, role) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;


-- ------------------------------------------------------------
-- 20260802000100_teacher_role_grant.sql
-- ------------------------------------------------------------
-- Ways to become a teacher other than "sign up with a teacher code".
--
-- Until now the teacher role could only ever be granted by handle_new_user at
-- the moment of account creation. That left two dead ends with no fix short of
-- editing the database by hand:
--
--   * A teacher who already has a student account (or who signed up with the
--     wrong code) can never be upgraded.
--   * The owner's own account, which predates the role system entirely, is a
--     teacher only by virtue of the hardcoded admin email.
--
-- This adds a self-serve redemption for logged-in users and an admin grant by
-- email address.

-- ============================================================
-- redeem_access_code_for_role — an existing signed-in user
-- redeems a privileged code to gain its role.
--
-- Deliberately refuses plain student codes: those exist to put someone in a
-- classroom at sign-up, and re-running that after the fact would not enroll
-- them anyway (membership keys off profiles.signup_access_code, which is set
-- once). Returning a clear error beats silently doing nothing.
-- ============================================================
CREATE OR REPLACE FUNCTION public.redeem_access_code_for_role(p_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_code text := upper(btrim(COALESCE(p_code, '')));
  v_id uuid;
  v_role public.app_role;
  v_expires_at timestamptz;
  v_redeemed uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'You must be signed in to redeem a code.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT id, grants_role, expires_at
    INTO v_id, v_role, v_expires_at
  FROM public.access_codes
  WHERE code = v_code
    AND is_active = TRUE
  LIMIT 1;

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'That code is not valid.'
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_expires_at IS NOT NULL AND v_expires_at <= now() THEN
    RAISE EXCEPTION 'That code has expired.'
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_role IS NULL OR v_role = 'user' THEN
    RAISE EXCEPTION 'That is a student code, not a teacher code.'
      USING ERRCODE = 'check_violation';
  END IF;

  -- Already holds it: succeed quietly without burning a redemption.
  IF EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = v_uid AND role = v_role) THEN
    RETURN jsonb_build_object('granted', false, 'role', v_role, 'already_held', true);
  END IF;

  UPDATE public.access_codes
  SET redeemed_count = redeemed_count + 1
  WHERE id = v_id
    AND (max_redemptions IS NULL OR redeemed_count < max_redemptions)
  RETURNING id INTO v_redeemed;

  IF v_redeemed IS NULL THEN
    RAISE EXCEPTION 'That code has already been used the maximum number of times.'
      USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (v_uid, v_role)
  ON CONFLICT (user_id, role) DO NOTHING;

  RETURN jsonb_build_object('granted', true, 'role', v_role, 'already_held', false);
END;
$$;

GRANT EXECUTE ON FUNCTION public.redeem_access_code_for_role(TEXT) TO authenticated;

-- ============================================================
-- admin_set_teacher_role — grant or revoke by email, for the
-- case where someone already has an account.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_set_teacher_role(p_email TEXT, p_grant BOOLEAN DEFAULT TRUE)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_target uuid;
  v_email text := lower(btrim(COALESCE(p_email, '')));
BEGIN
  IF NOT public.is_phil_admin() THEN
    RAISE EXCEPTION 'Admin access required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT id INTO v_target
  FROM auth.users
  WHERE lower(email) = v_email
  LIMIT 1;

  IF v_target IS NULL THEN
    RAISE EXCEPTION 'No account found for %', v_email
      USING ERRCODE = 'no_data_found';
  END IF;

  IF p_grant THEN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (v_target, 'teacher')
    ON CONFLICT (user_id, role) DO NOTHING;
  ELSE
    DELETE FROM public.user_roles
    WHERE user_id = v_target AND role = 'teacher';
  END IF;

  RETURN jsonb_build_object('user_id', v_target, 'email', v_email, 'is_teacher', p_grant);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_teacher_role(TEXT, BOOLEAN) TO authenticated;

-- ============================================================
-- admin_list_teachers — who currently holds the role, and how
-- many classes they run. Lets the admin panel answer "did that
-- teacher's code actually work?" without a SQL console.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_list_teachers()
RETURNS TABLE (
  user_id UUID,
  email TEXT,
  username TEXT,
  created_at TIMESTAMPTZ,
  classroom_count BIGINT,
  student_count BIGINT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_phil_admin() THEN
    RAISE EXCEPTION 'Admin access required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN QUERY
  SELECT
    ur.user_id,
    p.email::text,
    p.username::text,
    p.created_at,
    (SELECT COUNT(*) FROM public.classrooms c WHERE c.teacher_id = ur.user_id),
    (SELECT COUNT(*)
       FROM public.classroom_members cm
       JOIN public.classrooms c2 ON c2.id = cm.classroom_id
      WHERE c2.teacher_id = ur.user_id AND cm.status = 'active')
  FROM public.user_roles ur
  LEFT JOIN public.profiles p ON p.id = ur.user_id
  WHERE ur.role = 'teacher'
  ORDER BY p.created_at DESC NULLS LAST;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_teachers() TO authenticated;


-- ------------------------------------------------------------
-- 20260802000200_assessment_responses.sql
-- ------------------------------------------------------------
-- Item-level answer capture.
--
-- The app already asks students a lot of scenario questions — personal finance
-- lesson quizzes, village knowledge checks, economics checks — and until now
-- every one of those answers was discarded the moment the component unmounted.
-- Only the aggregate score survived, rolled into a module percentage, so a
-- teacher could see *that* a student scored 60% and never *which* misconception
-- cost them the other 40%.
--
-- One row per answered item. The column that earns this table its keep is
-- selected_label: knowing a student picked "the employer made an error" rather
-- than simply "got it wrong" turns a score into a diagnosis.

CREATE TABLE IF NOT EXISTS public.assessment_responses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- One uuid per quiz run, minted client-side. Makes the write idempotent so a
  -- re-render or a retried request cannot double-count an answer.
  attempt_id UUID NOT NULL,

  -- 'lesson_quiz' today; 'pre_test' / 'post_test' / 'test_out' are reserved for
  -- the pre/post instrument in agents/education/ASSESSMENT_SPEC.md.
  instrument TEXT NOT NULL DEFAULT 'lesson_quiz',

  module_type TEXT NOT NULL,
  module_id TEXT,
  lesson_id TEXT NOT NULL,

  -- Village questions carry their own ids; personal-finance and economics
  -- questions do not, so those synthesise "<lesson_id>#<index>". Stable as long
  -- as question order within a lesson is stable.
  item_id TEXT NOT NULL,
  item_index INTEGER,

  -- Snapshots of the wording as the student saw it. Denormalised on purpose:
  -- the content is static TS that ships with the bundle, so without a copy here
  -- an edit to a question would silently rewrite the history of what was asked.
  prompt TEXT,
  selected_key TEXT,
  selected_label TEXT,
  correct_key TEXT,
  correct_label TEXT,

  is_correct BOOLEAN NOT NULL,
  ms_elapsed INTEGER,

  -- Reserved for the concept taxonomy. Nothing populates it yet.
  concept_id TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (user_id, attempt_id, item_id)
);

CREATE INDEX IF NOT EXISTS assessment_responses_user_idx
  ON public.assessment_responses(user_id);
CREATE INDEX IF NOT EXISTS assessment_responses_item_idx
  ON public.assessment_responses(module_type, lesson_id, item_id);
CREATE INDEX IF NOT EXISTS assessment_responses_created_idx
  ON public.assessment_responses(created_at DESC);

ALTER TABLE public.assessment_responses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own assessment responses" ON public.assessment_responses;
CREATE POLICY "Users can view own assessment responses"
  ON public.assessment_responses FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own assessment responses" ON public.assessment_responses;
CREATE POLICY "Users can insert own assessment responses"
  ON public.assessment_responses FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Teachers never read this table directly; they go through the SECURITY
-- DEFINER functions below, which authorize against classroom ownership first.

-- ============================================================
-- record_assessment_responses — batch write for the caller.
-- The whole quiz posts once, on completion.
-- ============================================================
CREATE OR REPLACE FUNCTION public.record_assessment_responses(p_entries JSONB)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_count integer := 0;
BEGIN
  IF v_uid IS NULL THEN
    RETURN 0;
  END IF;

  IF p_entries IS NULL OR jsonb_typeof(p_entries) <> 'array' THEN
    RETURN 0;
  END IF;

  INSERT INTO public.assessment_responses (
    user_id, attempt_id, instrument, module_type, module_id, lesson_id,
    item_id, item_index, prompt, selected_key, selected_label,
    correct_key, correct_label, is_correct, ms_elapsed, concept_id
  )
  SELECT
    v_uid,
    (e ->> 'attempt_id')::uuid,
    COALESCE(NULLIF(e ->> 'instrument', ''), 'lesson_quiz'),
    e ->> 'module_type',
    NULLIF(e ->> 'module_id', ''),
    e ->> 'lesson_id',
    e ->> 'item_id',
    NULLIF(e ->> 'item_index', '')::integer,
    NULLIF(e ->> 'prompt', ''),
    NULLIF(e ->> 'selected_key', ''),
    NULLIF(e ->> 'selected_label', ''),
    NULLIF(e ->> 'correct_key', ''),
    NULLIF(e ->> 'correct_label', ''),
    COALESCE((e ->> 'is_correct')::boolean, false),
    NULLIF(e ->> 'ms_elapsed', '')::integer,
    NULLIF(e ->> 'concept_id', '')
  FROM jsonb_array_elements(p_entries) AS e
  WHERE e ->> 'attempt_id' IS NOT NULL
    AND e ->> 'module_type' IS NOT NULL
    AND e ->> 'lesson_id' IS NOT NULL
    AND e ->> 'item_id' IS NOT NULL
  ON CONFLICT (user_id, attempt_id, item_id) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

GRANT EXECUTE ON FUNCTION public.record_assessment_responses(JSONB) TO authenticated;

-- ============================================================
-- teacher_get_question_breakdown — the distractor analysis.
--
-- For every scenario the class has answered, which option each student chose.
-- Only the student's most recent attempt at an item counts, so a retry after
-- review shows what they understand now rather than what they got wrong first.
-- ============================================================
CREATE OR REPLACE FUNCTION public.teacher_get_question_breakdown(
  p_classroom_id UUID,
  p_module_type TEXT DEFAULT NULL
)
RETURNS TABLE (
  module_type TEXT,
  module_id TEXT,
  lesson_id TEXT,
  item_id TEXT,
  prompt TEXT,
  correct_label TEXT,
  response_count BIGINT,
  correct_count BIGINT,
  options JSONB
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN QUERY
  WITH members AS (
    SELECT cm.student_id
    FROM public.classroom_members cm
    WHERE cm.classroom_id = p_classroom_id
      AND cm.status = 'active'
  ),
  latest AS (
    SELECT DISTINCT ON (ar.user_id, ar.module_type, ar.lesson_id, ar.item_id)
      ar.user_id,
      ar.module_type,
      ar.module_id,
      ar.lesson_id,
      ar.item_id,
      ar.prompt,
      ar.selected_key,
      ar.selected_label,
      ar.correct_label,
      ar.is_correct
    FROM public.assessment_responses ar
    JOIN members m ON m.student_id = ar.user_id
    WHERE (p_module_type IS NULL OR ar.module_type = p_module_type)
    ORDER BY ar.user_id, ar.module_type, ar.lesson_id, ar.item_id, ar.created_at DESC
  ),
  per_option AS (
    SELECT
      l.module_type,
      l.lesson_id,
      l.item_id,
      COALESCE(l.selected_label, '(no answer)') AS label,
      bool_or(l.is_correct) AS option_is_correct,
      COUNT(*) AS option_count,
      jsonb_agg(
        jsonb_build_object(
          'student_id', l.user_id,
          'username', COALESCE(pr.username, 'Student')
        )
        ORDER BY COALESCE(pr.username, 'Student')
      ) AS students
    FROM latest l
    LEFT JOIN public.profiles pr ON pr.id = l.user_id
    GROUP BY l.module_type, l.lesson_id, l.item_id, COALESCE(l.selected_label, '(no answer)')
  )
  SELECT
    l.module_type,
    MAX(l.module_id)     AS module_id,
    l.lesson_id,
    l.item_id,
    MAX(l.prompt)        AS prompt,
    MAX(l.correct_label) AS correct_label,
    COUNT(*)                                          AS response_count,
    COUNT(*) FILTER (WHERE l.is_correct)              AS correct_count,
    COALESCE((
      SELECT jsonb_agg(
               jsonb_build_object(
                 'label', po.label,
                 'is_correct', po.option_is_correct,
                 'count', po.option_count,
                 'students', po.students
               )
               ORDER BY po.option_count DESC, po.label
             )
      FROM per_option po
      WHERE po.module_type = l.module_type
        AND po.lesson_id = l.lesson_id
        AND po.item_id = l.item_id
    ), '[]'::jsonb) AS options
  FROM latest l
  GROUP BY l.module_type, l.lesson_id, l.item_id
  -- Most-missed first: this is a "what do I reteach tomorrow" list, not a catalogue.
  ORDER BY (COUNT(*) - COUNT(*) FILTER (WHERE l.is_correct)) DESC, l.lesson_id, l.item_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_question_breakdown(UUID, TEXT) TO authenticated;

-- ============================================================
-- teacher_get_student_responses — the same data for one student,
-- for the roster detail sheet. Wrong answers first.
-- ============================================================
CREATE OR REPLACE FUNCTION public.teacher_get_student_responses(
  p_classroom_id UUID,
  p_student_id UUID,
  p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
  module_type TEXT,
  lesson_id TEXT,
  item_id TEXT,
  prompt TEXT,
  selected_label TEXT,
  correct_label TEXT,
  is_correct BOOLEAN,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.classroom_members cm
    WHERE cm.classroom_id = p_classroom_id
      AND cm.student_id = p_student_id
  ) THEN
    RAISE EXCEPTION 'Student is not in this classroom'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN QUERY
  SELECT DISTINCT ON (ar.module_type, ar.lesson_id, ar.item_id)
    ar.module_type,
    ar.lesson_id,
    ar.item_id,
    ar.prompt,
    ar.selected_label,
    ar.correct_label,
    ar.is_correct,
    ar.created_at
  FROM public.assessment_responses ar
  WHERE ar.user_id = p_student_id
  ORDER BY ar.module_type, ar.lesson_id, ar.item_id, ar.created_at DESC
  LIMIT GREATEST(COALESCE(p_limit, 50), 1);
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_student_responses(UUID, UUID, INTEGER) TO authenticated;


-- ------------------------------------------------------------
-- 20260802000300_teacher_teachback.sql
-- ------------------------------------------------------------
-- Teach-back proficiency for the teacher dashboard.
--
-- Teach Phil is the one place in the app where a student has to explain a
-- concept in their own words and gets graded on whether the explanation held
-- up. That makes teach_back_sessions the closest thing to a real measure of
-- understanding the product collects, and none of it reached the teacher: the
-- class insights panel aggregated missed facts across the whole class, so you
-- could see the class was shaky on something without seeing who.
--
-- Returns one payload with three views of the same sessions — per student, per
-- lesson, and a class summary — because the dashboard shows all three together
-- and three round trips for one panel is silly.

CREATE OR REPLACE FUNCTION public.teacher_get_teachback_overview(p_classroom_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  WITH members AS (
    SELECT cm.student_id
    FROM public.classroom_members cm
    WHERE cm.classroom_id = p_classroom_id
      AND cm.status = 'active'
  ),
  sessions AS (
    SELECT tb.*
    FROM public.teach_back_sessions tb
    JOIN members m ON m.student_id = tb.user_id
  ),
  -- Every missed fact, one row per (session, fact), so it can be counted both
  -- by student and by lesson without re-expanding the jsonb twice.
  misses AS (
    SELECT s.user_id, s.lesson_id, f.fact
    FROM sessions s
    CROSS JOIN LATERAL jsonb_array_elements_text(s.key_facts_missing) AS f(fact)
  ),
  student_rows AS (
    SELECT
      m.student_id,
      COALESCE(pr.username, 'Student') AS username,
      COUNT(s.id)                                        AS sessions,
      COUNT(s.id) FILTER (WHERE s.passed)                AS passed_sessions,
      COALESCE(ROUND(AVG(s.final_understanding_score)), 0) AS avg_score,
      COALESCE(MAX(s.final_understanding_score), 0)      AS best_score,
      MAX(s.created_at)                                  AS last_at,
      COUNT(DISTINCT s.lesson_id)                        AS lessons_attempted
    FROM members m
    LEFT JOIN public.profiles pr ON pr.id = m.student_id
    LEFT JOIN sessions s ON s.user_id = m.student_id
    GROUP BY m.student_id, pr.username
  ),
  lesson_rows AS (
    SELECT
      s.lesson_id,
      COUNT(*)                                           AS sessions,
      COUNT(DISTINCT s.user_id)                          AS student_count,
      COALESCE(ROUND(AVG(s.final_understanding_score)), 0) AS avg_score,
      COUNT(*) FILTER (WHERE s.passed)                   AS passed_sessions
    FROM sessions s
    GROUP BY s.lesson_id
  )
  SELECT jsonb_build_object(
    'summary', (
      SELECT jsonb_build_object(
        'sessions', COUNT(*),
        'students_attempted', COUNT(DISTINCT user_id),
        'avg_score', COALESCE(ROUND(AVG(final_understanding_score)), 0),
        'pass_rate', CASE WHEN COUNT(*) = 0 THEN 0
                          ELSE ROUND(100.0 * COUNT(*) FILTER (WHERE passed) / COUNT(*))
                     END
      )
      FROM sessions
    ),
    'students', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'student_id', sr.student_id,
          'username', sr.username,
          'sessions', sr.sessions,
          'passed_sessions', sr.passed_sessions,
          'avg_score', sr.avg_score,
          'best_score', sr.best_score,
          'lessons_attempted', sr.lessons_attempted,
          'last_at', sr.last_at,
          'top_missed', COALESCE((
            SELECT jsonb_agg(t.fact ORDER BY t.n DESC, t.fact)
            FROM (
              SELECT mi.fact, COUNT(*) AS n
              FROM misses mi
              WHERE mi.user_id = sr.student_id
              GROUP BY mi.fact
              ORDER BY COUNT(*) DESC, mi.fact
              LIMIT 4
            ) t
          ), '[]'::jsonb)
        )
        ORDER BY sr.sessions DESC, sr.avg_score DESC, sr.username
      )
      FROM student_rows sr
    ), '[]'::jsonb),
    'lessons', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'lesson_id', lr.lesson_id,
          'sessions', lr.sessions,
          'student_count', lr.student_count,
          'avg_score', lr.avg_score,
          'pass_rate', CASE WHEN lr.sessions = 0 THEN 0
                            ELSE ROUND(100.0 * lr.passed_sessions / lr.sessions)
                       END,
          'top_missed', COALESCE((
            SELECT jsonb_agg(jsonb_build_object('fact', t.fact, 'count', t.n)
                             ORDER BY t.n DESC, t.fact)
            FROM (
              SELECT mi.fact, COUNT(*) AS n
              FROM misses mi
              WHERE mi.lesson_id = lr.lesson_id
              GROUP BY mi.fact
              ORDER BY COUNT(*) DESC, mi.fact
              LIMIT 5
            ) t
          ), '[]'::jsonb)
        )
        ORDER BY lr.avg_score ASC, lr.lesson_id
      )
      FROM lesson_rows lr
    ), '[]'::jsonb)
  )
  INTO v_result;

  RETURN COALESCE(v_result, jsonb_build_object(
    'summary', jsonb_build_object('sessions', 0, 'students_attempted', 0, 'avg_score', 0, 'pass_rate', 0),
    'students', '[]'::jsonb,
    'lessons', '[]'::jsonb
  ));
END;
$$;

GRANT EXECUTE ON FUNCTION public.teacher_get_teachback_overview(UUID) TO authenticated;


-- ------------------------------------------------------------
-- 20260803000000_module_progress_test_scores.sql
-- ------------------------------------------------------------
-- Add the pre/post test columns to module_progress on projects that never got
-- them.
--
-- public.module_progress was created twice in this repo's history. The July
-- 2025 migration created it without test-score columns; the November 2025 one
-- lists them, but guards with CREATE TABLE IF NOT EXISTS, so on any project
-- where July ran first it is a no-op and the columns never appear. The
-- accompanying November migration patched last_accessed and completed_at the
-- same way but omitted these two, so the drift went unnoticed until
-- teacher_get_student_detail read them and failed with
-- "column mp.pre_test_score does not exist".
--
-- Adding them here rather than removing the references from the dashboard
-- keeps one schema across projects: the generated Supabase types and the
-- November definition both say these columns exist, and they are where a
-- pre/post test flow is expected to write its scores. Until such a flow exists
-- they stay NULL, which the dashboard already renders as "no score yet".

ALTER TABLE public.module_progress
  ADD COLUMN IF NOT EXISTS pre_test_score INTEGER,
  ADD COLUMN IF NOT EXISTS post_test_score INTEGER,
  ADD COLUMN IF NOT EXISTS improvement_percentage INTEGER;


-- ------------------------------------------------------------
-- 20260909030744_teacher_learning_momentum.sql
-- ------------------------------------------------------------
-- A paired, evidence-based week-over-week learning measure for teachers.
--
-- "Learning score" is calculated per student first, so one student taking many
-- quizzes cannot dominate the class:
--   * scenario answers: percentage correct
--   * Ask Phil teach-backs: average understanding score
--   * when both exist: 70% scenarios + 30% teach-backs
--
-- A student-week needs at least three scenario answers or one teach-back. The
-- headline change compares only students with enough evidence in BOTH of the
-- latest two rolling 7-day windows. That paired cohort is important: otherwise
-- a different group of students signing in could look like learning growth.

CREATE OR REPLACE FUNCTION public.teacher_get_learning_momentum(
  p_classroom_id UUID,
  p_weeks INTEGER DEFAULT 6
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_weeks integer := LEAST(GREATEST(COALESCE(p_weeks, 6), 2), 12);
  v_result jsonb;
BEGIN
  IF NOT public.teacher_owns_classroom(p_classroom_id) THEN
    RAISE EXCEPTION 'Not your classroom'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  WITH members AS (
    SELECT cm.student_id
    FROM public.classroom_members cm
    WHERE cm.classroom_id = p_classroom_id
      AND cm.status = 'active'
  ),
  assessment AS (
    SELECT
      ar.user_id,
      FLOOR((CURRENT_DATE - ar.created_at::date) / 7.0)::integer AS bucket,
      ROUND(100.0 * COUNT(*) FILTER (WHERE ar.is_correct) / COUNT(*), 1) AS score,
      COUNT(*)::integer AS evidence
    FROM public.assessment_responses ar
    JOIN members m ON m.student_id = ar.user_id
    WHERE ar.created_at::date BETWEEN CURRENT_DATE - (v_weeks * 7 - 1) AND CURRENT_DATE
    GROUP BY ar.user_id, FLOOR((CURRENT_DATE - ar.created_at::date) / 7.0)::integer
  ),
  teachback AS (
    SELECT
      tb.user_id,
      FLOOR((CURRENT_DATE - tb.created_at::date) / 7.0)::integer AS bucket,
      ROUND(AVG(tb.final_understanding_score), 1) AS score,
      COUNT(*)::integer AS evidence
    FROM public.teach_back_sessions tb
    JOIN members m ON m.student_id = tb.user_id
    WHERE tb.created_at::date BETWEEN CURRENT_DATE - (v_weeks * 7 - 1) AND CURRENT_DATE
    GROUP BY tb.user_id, FLOOR((CURRENT_DATE - tb.created_at::date) / 7.0)::integer
  ),
  student_weeks AS (
    SELECT
      COALESCE(a.user_id, t.user_id) AS user_id,
      COALESCE(a.bucket, t.bucket) AS bucket,
      CASE
        WHEN a.score IS NOT NULL AND t.score IS NOT NULL
          THEN ROUND(a.score * 0.7 + t.score * 0.3, 1)
        ELSE COALESCE(a.score, t.score)
      END AS score,
      COALESCE(a.evidence, 0) AS assessment_items,
      COALESCE(t.evidence, 0) AS teachbacks
    FROM assessment a
    FULL JOIN teachback t
      ON t.user_id = a.user_id
     AND t.bucket = a.bucket
    WHERE COALESCE(a.evidence, 0) >= 3
       OR COALESCE(t.evidence, 0) >= 1
  ),
  buckets AS (
    SELECT generate_series(0, v_weeks - 1) AS bucket
  ),
  weekly AS (
    SELECT
      b.bucket,
      (CURRENT_DATE - (b.bucket * 7 + 6)) AS starts_on,
      (CURRENT_DATE - b.bucket * 7) AS ends_on,
      ROUND(AVG(sw.score), 1) AS score,
      COUNT(sw.user_id)::integer AS students,
      COALESCE(SUM(sw.assessment_items), 0)::integer AS assessment_items,
      COALESCE(SUM(sw.teachbacks), 0)::integer AS teachbacks
    FROM buckets b
    LEFT JOIN student_weeks sw ON sw.bucket = b.bucket
    GROUP BY b.bucket
  ),
  paired AS (
    SELECT
      COUNT(*)::integer AS students,
      ROUND(AVG(current_week.score - prior_week.score), 1) AS change
    FROM student_weeks current_week
    JOIN student_weeks prior_week
      ON prior_week.user_id = current_week.user_id
     AND prior_week.bucket = 1
    WHERE current_week.bucket = 0
  )
  SELECT jsonb_build_object(
    'metric_name', 'Learning Momentum',
    'minimum_paired_students', 3,
    'current_score', (SELECT score FROM weekly WHERE bucket = 0),
    'paired_students', (SELECT students FROM paired),
    'week_over_week_change', CASE
      WHEN (SELECT students FROM paired) >= 3 THEN (SELECT change FROM paired)
      ELSE NULL
    END,
    'weeks', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'starts_on', w.starts_on,
          'ends_on', w.ends_on,
          'score', w.score,
          'students', w.students,
          'assessment_items', w.assessment_items,
          'teachbacks', w.teachbacks
        )
        ORDER BY w.bucket DESC
      )
      FROM weekly w
    ), '[]'::jsonb)
  )
  INTO v_result;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.teacher_get_learning_momentum(UUID, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.teacher_get_learning_momentum(UUID, INTEGER) FROM anon;
GRANT EXECUTE ON FUNCTION public.teacher_get_learning_momentum(UUID, INTEGER) TO authenticated;


-- ------------------------------------------------------------
-- 20260909030809_teacher_dashboard_tour_state.sql
-- ------------------------------------------------------------
-- Keep the teacher dashboard walkthrough completion state per account so it
-- follows a teacher across devices. Replay does not clear this flag; it simply
-- opens the walkthrough on demand.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS teacher_dashboard_tour_completed BOOLEAN NOT NULL DEFAULT FALSE;
