-- ============================================================
-- TEACHER SETUP — PART 1 OF 2
--
-- Paste this whole file into the Supabase SQL editor and run it.
-- It adds one value to an enum and finishes in well under a second.
--
-- Then open a NEW query tab and run part 2. Running them in the same
-- tab fails, because part 2 uses the enum value part 1 creates.
--
-- Source: supabase/migrations/20260801000000_teacher_role_enum.sql
--
-- Generated by scripts/build-teacher-sql.mjs — do not edit by hand.
-- Edit the files in supabase/migrations and regenerate.
-- ============================================================

-- Add the 'teacher' value to the app_role enum.
--
-- This lives in its own migration on purpose: Postgres will not let a newly
-- added enum value be *used* in the same transaction that adds it, and each
-- migration file runs in one transaction. Everything that references
-- 'teacher' therefore has to land in a later file.

ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'teacher';
