import { describe, it, expect, beforeEach } from 'vitest';
import {
  unlockMILessonFlashcards,
  getUnlockedMIFlashcardIds,
  unlockCareersFlashcards,
  getUnlockedCareersFlashcardIds,
  unlockCareersLessonFlashcards,
  getAvailableFlashcards,
  getSubcategoryUnlockStatus,
} from './flashcardUnlockStore';
import type { UnifiedFlashcard } from '@/data/unified-flashcards';

// Minimal MI lesson fixture
const makeLesson = (id: string) => ({
  id,
  moduleId: id,
  section: 'ownership' as const,
  title: `Lesson ${id}`,
  estimatedMinutes: 5,
  intro: { hook: '', philMessage: '', heroImage: { src: '', alt: '' } },
  coreConcepts: [],
  tryItActivity: { type: 'scenario_choice' as const, prompt: '', choices: [] },
  connectToCareer: { career: '', connection: '', callToAction: '' },
  connectToPF: { topic: '', connection: '', callToAction: '' },
  flashcards: [
    { term: 'A', definition: 'Def A', philsAnalogy: 'Analogy A' },
    { term: 'B', definition: 'Def B', philsAnalogy: 'Analogy B' },
  ],
  quiz: [],
  rewards: { bamboo: 10, xp: 2 },
});

const makeCard = (id: string, source: UnifiedFlashcard['sourceModule'], sub?: string): UnifiedFlashcard => ({
  id,
  term: `Term ${id}`,
  definition: `Def ${id}`,
  sourceModule: source,
  category: source === 'careers' ? 'Investment Banking' : 'Finance',
  subcategory: sub ?? `Sub ${id}`,
  difficulty: 'beginner',
  tags: [],
  icon: '📚',
});

describe('flashcardUnlockStore', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  // ── MI unlocks ─────────────────────────────────────────────────────────────
  describe('MI unlocks', () => {
    it('starts with no unlocked MI ids', () => {
      expect(getUnlockedMIFlashcardIds().size).toBe(0);
    });

    it('unlocks MI flashcard IDs when lesson is unlocked', () => {
      const lesson = makeLesson('test-lesson');
      unlockMILessonFlashcards(lesson);
      const ids = getUnlockedMIFlashcardIds();
      expect(ids.size).toBe(2);
      expect(ids.has('mi-ownership-test-lesson-0')).toBe(true);
      expect(ids.has('mi-ownership-test-lesson-1')).toBe(true);
    });

    it('unlocking the same lesson twice does not duplicate IDs', () => {
      const lesson = makeLesson('dup-lesson');
      unlockMILessonFlashcards(lesson);
      unlockMILessonFlashcards(lesson);
      expect(getUnlockedMIFlashcardIds().size).toBe(2);
    });
  });

  // ── Careers unlocks ────────────────────────────────────────────────────────
  describe('Careers unlocks', () => {
    it('starts with no unlocked careers ids', () => {
      expect(getUnlockedCareersFlashcardIds().size).toBe(0);
    });

    it('unlocks specific card IDs', () => {
      unlockCareersFlashcards(['careers-ib-ipo', 'careers-pe-lbo']);
      const ids = getUnlockedCareersFlashcardIds();
      expect(ids.has('careers-ib-ipo')).toBe(true);
      expect(ids.has('careers-pe-lbo')).toBe(true);
    });

    it('unlockCareersLessonFlashcards matches by sourceLesson', () => {
      const allCards: UnifiedFlashcard[] = [
        makeCard('c1', 'careers'),
        makeCard('c2', 'careers'),
        makeCard('c3', 'market-intelligence'),
      ];
      (allCards[0] as { sourceLesson: string }).sourceLesson = 'Interview — Prepare';
      (allCards[1] as { sourceLesson: string }).sourceLesson = 'Interview — Deliver';

      unlockCareersLessonFlashcards('Interview — Prepare', allCards);

      const ids = getUnlockedCareersFlashcardIds();
      expect(ids.has('c1')).toBe(true);
      expect(ids.has('c2')).toBe(false);
      expect(ids.has('c3')).toBe(false);
    });
  });

  // ── getAvailableFlashcards ─────────────────────────────────────────────────
  describe('getAvailableFlashcards', () => {
    const pfCard = makeCard('pf1', 'personal-finance');
    const miCard = makeCard('mi1', 'market-intelligence');
    const cCard = makeCard('c1', 'careers');
    const allCards = [pfCard, miCard, cCard];

    it('returns all PF cards without unlock check', () => {
      const avail = getAvailableFlashcards('personal-finance', allCards);
      expect(avail).toEqual([pfCard]);
    });

    it('returns only unlocked MI cards', () => {
      const avail = getAvailableFlashcards('market-intelligence', allCards);
      expect(avail.length).toBe(0);

      unlockMILessonFlashcards(makeLesson('mi1'));
      // 'mi1' is not the format generated by makeLesson, so let's directly unlock
      unlockCareersFlashcards([]); // just to show it's separate
      localStorage.setItem('mi_unlocked_flashcard_ids', JSON.stringify(['mi1']));

      const avail2 = getAvailableFlashcards('market-intelligence', allCards);
      expect(avail2).toEqual([miCard]);
    });

    it('returns only unlocked Careers cards', () => {
      const avail = getAvailableFlashcards('careers', allCards);
      expect(avail.length).toBe(0);

      unlockCareersFlashcards(['c1']);

      const avail2 = getAvailableFlashcards('careers', allCards);
      expect(avail2).toEqual([cCard]);
    });
  });

  // ── getSubcategoryUnlockStatus ────────────────────────────────────────────
  describe('getSubcategoryUnlockStatus', () => {
    it('marks subcategories as locked when no IDs unlocked', () => {
      const cards: UnifiedFlashcard[] = [
        makeCard('c1', 'careers', 'IB Basics'),
        makeCard('c2', 'careers', 'IB Basics'),
      ];
      const statuses = getSubcategoryUnlockStatus('careers', cards);
      expect(statuses.length).toBe(1);
      expect(statuses[0].unlocked).toBe(false);
      expect(statuses[0].unlockCta).toContain('IB Basics');
    });

    it('marks subcategory as unlocked when any card ID is unlocked', () => {
      const cards: UnifiedFlashcard[] = [
        makeCard('c1', 'careers', 'IB Basics'),
        makeCard('c2', 'careers', 'IB Basics'),
      ];
      unlockCareersFlashcards(['c1']);
      const statuses = getSubcategoryUnlockStatus('careers', cards);
      expect(statuses[0].unlocked).toBe(true);
    });
  });
});
